{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-env
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: vllmdiffusiongemma26a4bone
    backend: vllm
data:
  MODEL_URL: "https://huggingface.co/google/gemma-4-26B-A4B-it/resolve/main/config.json"
  MODEL_FILE: "gemma-4-26B-A4B-it"
  MODEL_ALIAS: "diffusion-gemma-26b-a4b"
  CONTEXT_SIZE: "32768"
  LITELLM_MODEL_NAME: "diffusion-gemma-26b-a4b"
  LITELLM_SERVICE_URL: "http://litellm.litellmgatewayserver-shared:4000"
{{- end }}
